language: node_js
node_js:
- 14.11.0
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y texlive texlive-latex-extra texlive-bibtex-extra latexmk
install:
- yarn install
- gem install sass
script:
- yarn run grunt
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  verbose: true
  on:
    branch: master
env:
  global:
    secure: aV6/0AVamRrlRUKNlao8pk2sqBbMsl0HOXbvOwDVsUhDgaxDpX+xGLdWrBiAd3KySCel9WzGCunogKfprpfGHyqCtw46zkjn0EBPyANRLYswvT6lvzSi5RA1tdYPD5q32114enojZUHPzkqCmVraNu2GHw2Fr7dH8AE5e2FqV6sI/E09VtibkdyabQAiXXzg4aktJEFzFef6vfRKTzZxhn9wRgh6h0994eMcLFdCe70kBcyzpT3bKC9ZR/DmS9fBjSjPkun5iupZpfoWFBRqnS3Z0smeA0/a5H4C0E39cwANVsAnbo8Xkj1DBEfg2UzCFA/+jWe8Qj09l/q9aU7pRBnjcMVVZSFYU3GhI6mhyGflxyBtmf5VxKsyj1usgL5Tu3rSWywcT043KFA6LPsak4MOyyDuGDo9LH9qJAF1VSx7WZX0Lxc/BXyZdJMKwOgurZnNoQfpARywPiS5n+mysMQ3KwJgvjVqm1joG12wrQnWruaBKjL2qqa60zcBOCtQOwh5HnIM84Dhqgf5wDBwgNJIgP0TmHb4cfIr5+T5H6aT7vk4P3pvMHcbqkCXNxh+RQaN91w+GIsWySZ5p3QQUKX7GegHLSn6JItR0NGAWdhRPd/sZhDulmF9S9qER3MbIB0qnyTs3cbD6HNXj7T4KMp4gdmFjl5FngB+pd8NYAw=
